<?php 
echo "estoi mostradoooo";
/*
echo "<div class="col-xs-12">"
echo "	<div class="box">"
echo "	    <div class="box-header">"
echo "	        <h3 class="box-title">Mostra datos</h3>"
echo "	        <div class="box-tools">"
echo "	            <div class="input-group">"
echo "	                <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Buscar"/>"
echo "	                <div class="input-group-btn">"
echo "	                    <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>"
echo "	                </div>"
echo "	            </div>"
echo "	        </div>"
echo "	    </div><!-- /.box-header -->"
echo "	    <div class="box-body table-responsive no-padding">"
echo "	        <table class="table table-hover">"
echo "	            <tr>"
echo "	                <th>ID</th>"
echo "	                <th>User</th>"
echo "	                <th>Date</th>"
echo "	                <th>Status</th>"
echo "	                <th>Reason</th>"
echo "	            </tr>"
echo "               <tr>"
echo "                   <td>183</td>"
echo "                    <td>John Doe</td>"
echo "                    <td>11-7-2014</td>"
echo "                    <td><span class="label label-success">Approved</span></td>"
echo "                    <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>"
echo "                </tr>"
echo "               <tr>"
echo "                    <td>219</td>"
echo "                    <td>Jane Doe</td>"
echo "                    <td>11-7-2014</td>"
echo "                    <td><span class="label label-warning">Pending</span></td>"
echo "                    <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>"
echo "                </tr>"
echo "                <tr>"
echo "                    <td>657</td>"
echo "                    <td>Bob Doe</td>"
echo "                    <td>11-7-2014</td>"
echo "                    <td><span class="label label-primary">Approved</span></td>"
echo "                    <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>"
echo "                </tr>"
echo "                <tr>"
echo "                    <td>175</td>"
echo "                    <td>Mike Doe</td>"
echo "                    <td>11-7-2014</td>"
echo "                    <td><span class="label label-danger">Denied</span></td>"
echo "                    <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>"
echo "                </tr>"
echo "            </table>"
echo "        </div><!-- /.box-body -->"
echo "    </div><!-- /.box -->"
echo "</div>"*/
?>